### ISSUE TITLE
Decide on nixpkgs update policy

### ISSUE THREAD

**Issue by shlevy** [zalora/defnix#29]
Obviously, we should update the revision used by a given package every time we find a feature or bugfix we need that is not available in the currently-used version. Should we also periodically proactively test packages against newer versions and update them if all is well, or only update on-demand? If so, when?

cc @jekor

**Comment by jekor** [comment]
Once we can (efficiently) give every program on a system its own pinned version of nixpkgs I would never want to upgrade it until necessary. Getting something to build doesn't mean that we won't encounter runtime errors. When a program is running reliably we don't want to update it just to stay current: it has little to no benefit and the downsides of more work and unforeseen errors.

**Comment by shlevy** [comment]
We already can do that, see https://github.com/zalora/defnix/blob/master/nixpkgs/uncomposed.nix#L36-L82 for how. So I guess we'll go with that.
